from .t1_edepma_config import EDEPMA_CONFIG
from .t2_sma_config import SMA_CONFIG
from .t3_ima_config import IMA_CONFIG
from .t4_edepbu_config import EDEPBU_CONFIG
from .t5_ibu_config import IBU_CONFIG
from .t6_dofa_config import DOFA_CONFIG
from .t7_dca_config import DCA_CONFIG
from .t8_dll_config import DLL_CONFIG
from .t9_dcl_config import DCL_CONFIG
from .t10_dsc_config import DSC_CONFIG
from .t11_drr_config import DRR_CONFIG
from .t12_oibd_config import OIBD_CONFIG
from .t13_fi_config import FI_CONFIG
from .t14_fe_config import FE_CONFIG
from .t15_tdepma_config import TDEPMA_CONFIG
from .t16_zpf_config import ZPF_CONFIG
from .t17_dour_config import DOUR_CONFIG
from .t18_gc_config import GC_CONFIG
from .t19_oa_config import OA_CONFIG
from .t20_tl_config import TL_CONFIG
from .t21_ota_config import OTA_CONFIG
from .t22_tdepbu_config import TDEPBU_CONFIG
from .t23_pallo_config import PALLO_CONFIG
from .t24_rot_config import ROT_CONFIG
