DLL_CONFIG = {
    "method": "LLN",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "Cumulative",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "DIMA",
                "DIBU",
                "Ddofa",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 0.6135,
                "sumcasht_1": 2.98e-11,
                "diffcasht_1": 5.02e-12,
                "ddmpat_1": 3.66e-10,
                "ddmpat_12": 2.29e-18,
                "ddmpat_13": 6.46e-29,
                "DIMA": 0.4924,
                "DIBU": 1.0961,
                "Ddofa": 0.3626,
                "realr": -8.5213,
                "FAAB": 0.4011,
                "Public": 0.1323,
                "ruralare": 0.2004,
                "largcity": -0.2784,
                "market": 1.7242,
                "marketw": 97.0519,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "DIMA",
                "DIBU",
                "Ddofa",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -1.11e7,
                "sumcasht_1": -0.00024,
                "diffcasht_1": -0.00123,
                "ddmpat_1": 0.1907,
                "ddmpat_12": 1.16e-11,
                "ddmpat_13": -412e-22,
                "DIMA": 1013777,
                "DIBU": -659890,
                "Ddofa": 951614,
                "realr": 3.247e8,
                "FAAB": -6590658,
                "Public": 14494032,
                "ruralare": -344517,
                "largcity": 245538,
                "market": 8.334e8,
                "marketw": -663913,
            },
        },
    ],
}
