DSC_CONFIG = {
    "method": "LSG",
    "steps": [
        {
            # --- Step 1: Positive Probability Model ---
            # Source: Table 10a: Logistic model with complementary log-log function
            "name": "positive_probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "DIMA",
                "DIBU",
                "Ddofa",
                "Ddll",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -2.1160,
                "sumcasht_1": -125e-12,
                "diffcasht_1": -365e-13,
                "ddmpat_1": 3.022e-9,
                "ddmpat_12": -339e-20,
                "ddmpat_13": -49e-29,
                "DIMA": 0.1965,
                "DIBU": 0.3457,
                "Ddofa": 0.6536,
                "Ddll": -0.1320,
                "realr": 1.5237,
                "FAAB": -0.1120,
                "Public": 1.1631,
                "ruralare": -0.0727,
                "largcity": 0.0940,
                "market": 3.1124,
                "marketw": -113.7,
            },
        },
        {
            # --- Step 2: Negative Probability Model ---
            # Source: Table 10b: Logistic model with complementary log-log function
            "name": "negative_probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "DIMA",
                "DIBU",
                "Ddofa",
                "Ddll",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -4.8439,
                "sumcasht_1": 1.53e-10,
                "diffcasht_1": 7.72e-11,
                "ddmpat_1": -1.22e-8,
                "ddmpat_12": -319e-19,
                "ddmpat_13": 4.19e-26,
                "DIMA": -0.0460,
                "DIBU": 1.1420,
                "Ddofa": 1.6523,
                "Ddll": 0.3261,
                "realr": -0.2649,
                "FAAB": 0.4363,
                "Public": -0.3393,
                "ruralare": -0.1496,
                "largcity": 0.0830,
                "market": -251.9,
                "marketw": 8.9469,
            },
        },
        {
            # --- Step 3: Positive Level Model ---
            # Source: Table 10c: Schweppe Bounded-Influence Regression using IRLS
            "name": "positive_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "DIMA",
                "DIBU",
                "Ddofa",
                "Ddll",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 978406,
                "sumcasht_1": 0.00230,
                "diffcasht_1": 0.000645,
                "ddmpat_1": 0.0741,
                "ddmpat_12": -139e-12,
                "DIMA": -9809.5,
                "DIBU": 2452522,
                "Ddofa": 2184568,
                "Ddll": 878469,
                "realr": 15982915,
                "FAAB": -4293344,
                "Public": 9963197,
                "ruralare": -518435,
                "largcity": 699912,
                "market": 1.9802e8,
                "marketw": 19733601,
            },
        },
        {
            # --- Step 4: Negative Level Model ---
            # Source: Table 10d: Schweppe Bounded-Influence Regression using IRLS
            "name": "negative_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "DIMA",
                "DIBU",
                "Ddofa",
                "Ddll",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -7898247,
                "sumcasht_1": -0.0732,
                "diffcasht_1": -0.0245,
                "ddmpat_1": 0.1962,
                "DIMA": -170817,
                "DIBU": -1436539,
                "Ddofa": -1596384,
                "Ddll": -655005,
                "realr": 1.2084e8,
                "FAAB": 1438075,
                "Public": -750417,
                "ruralare": -379241,
                "largcity": -1167779,
                "market": 3.9413e9,
                "marketw": -1.916e9,
            },
        },
    ],
}
