DRR_CONFIG = {
    "method": "LLG",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "ddmcasht_1",
                "ddmcasht_12",
                "DIMA",
                "DIBU",
                "Ddofa",
                "Ddll",
                "Ddsc",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -1.6031,
                "ddmcasht_1": -658e-14,
                "ddmcasht_12": 1.11e-21,
                "DIMA": 0.0490,
                "DIBU": 0.3412,
                "Ddofa": 0.2590,
                "Ddll": 0.1141,
                "Ddsc": 1.2387,
                "realr": 2.7568,
                "FAAB": 0.2314,
                "Public": 0.3820,
                "ruralare": -0.00198,
                "largcity": 0.00792,
                "market": -1.4597,
                "marketw": -4.8003,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "ddmcasht_1",
                "ddmcasht_12",
                "DIMA",
                "DIBU",
                "Ddofa",
                "Ddll",
                "Ddsc",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -388638,
                "ddmcasht_1": -0.00398,
                "ddmcasht_12": -181e-15,
                "DIMA": 319810,
                "DIBU": -66042.4,
                "Ddofa": 233849,
                "Ddll": -261543,
                "Ddsc": 500336,
                "realr": 17095738,
                "FAAB": -1440296,
                "Public": 19922935,
                "ruralare": -110096,
                "largcity": 279199,
                "market": 5.5484e8,
                "marketw": -2.181e8,
            },
        },
    ],
}
