OIBD_CONFIG = {
    "method": "HS",
    "description": "Estimation for Operating Income Before Depreciation based on Table 12a (page 212).",
    "steps": [
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumcaclt_1",
                "diffcaclt_1",
                "MAt_1",
                "I_MAt",
                "SMAt",
                "EDEPMAt",
                "EDEPMAt2",
                "BUt_1",
                "I_BUt",
                "EDEPBUt",
                "EDEPBUt2",
                "dcat",
                "dcat2",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "dcasht_1",
                "dcasht_12",
                "dclt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 346731,
                "sumcaclt_1": 0.000305,
                "diffcaclt_1": 0.000872,
                "MAt_1": 0.0426,
                "I_MAt": 0.0658,
                "SMAt": -0.0426,
                "EDEPMAt": 1.6231,
                "EDEPMAt2": -295e-12,
                "BUt_1": 0.0511,
                "I_BUt": 0.0510,
                "EDEPBUt": 1.3327,
                "EDEPBUt2": 1.495e-9,
                "dcat": 0.000746,
                "dcat2": -334e-16,
                "ddmpat_1": 0.00103,
                "ddmpat_12": -477e-14,
                "ddmpat_13": 1.62e-21,
                "dcasht_1": 0.000016,
                "dcasht_12": 1.45e-15,
                "dclt": -0.00024,
                "dgnp": -2.29e-6,
                "FAAB": -40563.6,
                "Public": -4662610,
                "ruralare": -111537,
                "largcity": 22275.8,
                "market": 3.2605e8,
                "marketw": -1.47e7,
            },
        }
    ],
}
