FI_CONFIG = {
    "method": "LLG",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "I_BUt",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "I_MAt",
                "I_MAt2",
                "EDEPBUt",
                "EDEPBUt2",
                "dcat",
                "dcat2",
                "dofat",
                "OFAt_1",
                "CAt_1",
                "MAt_1",
                "BUt_1",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 0.4339,
                "I_BUt": 1.645e-9,
                "EDEPMAt": 2.391e-8,
                "EDEPMAt2": -614e-20,
                "SMAt": 1.235e-9,
                "I_MAt": 2.254e-9,
                "I_MAt2": -3.04e-21,
                "EDEPBUt": 2.87e-8,
                "EDEPBUt2": -4.17e-18,
                "dcat": 1.43e-9,
                "dcat2": 7.35e-21,
                "dofat": 7.37e-12,
                "OFAt_1": 6.66e-11,
                "CAt_1": 1.422e-9,
                "MAt_1": -875e-12,
                "BUt_1": 2.1e-9,
                "realr": 3.1024,
                "FAAB": 0.1562,
                "Public": 0.6142,
                "ruralare": 0.0185,
                "largcity": 0.0502,
                "market": 36.9863,
                "marketw": -1.5806,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "I_BUt",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "I_MAt",
                "I_MAt2",
                "EDEPBUt",
                "EDEPBUt2",
                "dcat",
                "dcat2",
                "dofat",
                "OFAt_1",
                "CAt_1",
                "MAt_1",
                "BUt_1",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -14640.6,
                "I_BUt": 0.00945,
                "EDEPMAt": -0.0546,
                "EDEPMAt2": 4.19e-10,
                "SMAt": 0.0138,
                "I_MAt": -0.0111,
                "I_MAt2": 1.29e-11,
                "EDEPBUt": -0.3063,
                "EDEPBUt2": 3.2e-9,
                "dcat": 0.0245,
                "dcat2": -1.28e-15,
                "dofat": 0.0414,
                "OFAt_1": 0.0418,
                "CAt_1": 0.0251,
                "MAt_1": -0.0134,
                "BUt_1": 0.00916,
                "realr": 1122468,
                "FAAB": 110718,
                "Public": 992812,
                "ruralare": -26553.7,
                "largcity": -14437.0,
                "market": -4225702,
                "marketw": -2189313,
            },
        },
    ],
}
