FE_CONFIG = {
    "method": "LLG",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "I_BUt",
                "EDEPMAt",
                "SMAt",
                "I_MAt",
                "EDEPBUt",
                "OFAt_1",
                "MAt_1",
                "BUt_1",
                "LLt_1",
                "sumcaclt_1",
                "diffcaclt_1",
                "sumdcadclt",
                "diffdcadclt",
                "sumdofadllt",
                "diffdofadllt",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 0.7403,
                "I_BUt": 1.516e-9,
                "EDEPMAt": 2.567e-8,
                "SMAt": -769e-13,
                "I_MAt": 7.18e-10,
                "EDEPBUt": 1.508e-8,
                "OFAt_1": -159e-12,
                "MAt_1": -153e-13,
                "BUt_1": 1.946e-9,
                "LLt_1": 5.71e-10,
                "sumcaclt_1": 2.68e-10,
                "diffcaclt_1": -26e-11,
                "sumdcadclt": 1.51e-10,
                "diffdcadclt": -175e-12,
                "sumdofadllt": 1.7e-10,
                "diffdofadllt": -261e-12,
                "realr": -1.9037,
                "FAAB": 0.1900,
                "Public": 0.4724,
                "ruralare": 0.0953,
                "largcity": -0.1258,
                "market": 12.2057,
                "marketw": 0.8544,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "I_BUt",
                "EDEPMAt",
                "SMAt",
                "I_MAt",
                "EDEPBUt",
                "OFAt_1",
                "MAt_1",
                "BUt_1",
                "LLt_1",
                "sumcaclt_1",
                "diffcaclt_1",
                "sumdcadclt",
                "diffdcadclt",
                "sumdofadllt",
                "diffdofadllt",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -182379,
                "I_BUt": 0.0217,
                "EDEPMAt": 0.0839,
                "SMAt": -0.00676,
                "I_MAt": -0.0210,
                "EDEPBUt": 0.1914,
                "OFAt_1": 0.0145,
                "MAt_1": 0.00653,
                "BUt_1": 0.0212,
                "LLt_1": 0.0349,
                "sumcaclt_1": 0.00815,
                "diffcaclt_1": -0.0183,
                "sumdcadclt": 0.00795,
                "diffdcadclt": -0.0176,
                "sumdofadllt": 0.0244,
                "diffdofadllt": -0.0102,
                "realr": 4025817,
                "FAAB": 33749.7,
                "Public": 534338,
                "ruralare": 3376.6,
                "largcity": 31715.9,
                "market": -2122201,
                "marketw": -1.027e7,
            },
        },
    ],
}
