ZPF_CONFIG = {
    "method": "LLG",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "PALLOt_1",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "DTDEPMA",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -1.9046,
                "sumcasht_1": -41e-12,
                "diffcasht_1": -561e-15,
                "PALLOt_1": 1.567e-9,
                "ddmpat_1": 4.254e-9,
                "ddmpat_12": -807e-19,
                "ddmpat_13": -225e-28,
                "DTDEPMA": 0.3745,
                "realr": -22.4922,
                "FAAB": 0.3961,
                "Public": -0.2431,
                "ruralare": 0.0698,
                "largcity": 0.0470,
                "market": -84.4650,
                "marketw": 0.3594,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "PALLOt_1",
                "ddmpat_1",
                "DTDEPMA",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 417800,
                "sumcasht_1": 0.000464,
                "diffcasht_1": -0.00011,
                "PALLOt_1": 0.1053,
                "ddmpat_1": -0.0106,
                "DTDEPMA": 9917.2,
                "realr": -3668399,
                "FAAB": -168141,
                "Public": 934196,
                "ruralare": -40800.4,
                "largcity": 91246.9,
                "market": 1.5706e8,
                "marketw": 1.6632e8,
            },
        },
    ],
}
