DOUR_CONFIG = {
    "method": "MUNO",
    "steps": [
        {
            # --- Step 1: Multinomial Probability Model ---
            # Source: Table 17a: Multinomial Logit
            "name": "probability_model",
            "type": "Multinomial",
            "distribution": "clog-log",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "ddmpat_13",
                "DTDEPMA",
                "DZPF",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept1": [-2.1685, 1.06147],
                "sumcasht_1": -46e-12,
                "diffcasht_1": -15e-12,
                "ddmpat_1": 1.11e-9,
                "ddmpat_12": 309e-24,
                "ddmpat_13": -6e-29,
                "DTDEPMA": -0.3132,
                "DZPF": -0.3576,
                "realr": -4.8872,
                "FAAB": -0.1380,
                "Public": 0.07302,
                "ruralare": -0.0182,
                "largcity": 0.03468,
                "market": 1.33087,
                "marketw": -10.725,
            },
        },
        {
            # --- Step 2: Positive Level Model ---
            # Source: Table 17b: Estimating the level of positive dour
            "name": "positive_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "ddmpat_12",
                "DTDEPMA",
                "DZPF",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 865762,
                "sumcasht_1": 0.000251,
                "diffcasht_1": -0.00006,
                "ddmpat_1": 0.0146,
                "ddmpat_12": 3.91e-11,
                "DTDEPMA": 461104,
                "DZPF": 63314.1,
                "realr": 3675150,
                "FAAB": -1186295,
                "Public": 4038992,
                "ruralare": -53932.7,
                "largcity": 194704,
                "market": 4.3597e8,
                "marketw": 26167997,
            },
        },
        {
            # --- Step 3: Negative Level Model ---
            # Source: Table 17c: Estimating the level of negative dour
            "name": "negative_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "ddmpat_1",
                "DTDEPMA",
                "DZPF",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -364671,
                "sumcasht_1": -0.00702,
                "diffcasht_1": -0.00179,
                "ddmpat_1": -0.00040,
                "DTDEPMA": 5239.5,
                "DZPF": 49005.8,
                "realr": 945978,
                "FAAB": 128361,
                "Public": -315251,
                "ruralare": 7924.2,
                "largcity": -28112.8,
                "market": 1.689e8,
                "marketw": -4.151e8,
            },
        },
    ],
}
