GC_CONFIG = {
    "method": "LSG",  # The paper states LSG method gives the best prediction.
    "steps": [
        {
            # --- Step 1: Positive Probability Model (from Table 18a) ---
            "name": "positive_probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "OIBDt",
                "OIBDt2",
                "OIBDt3",
                "FIt",
                "FEt",
                "TDEPMAt",
                "TDEPMAt2",
                "EDEPBUt",
                "EDEPBUt2",
                "ZPFt",
                "dourt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
            ],
            "coefficients": {
                "Intercept": -2.3275,
                "OIBDt": -6.56e-9,
                "OIBDt2": 7.36e-19,
                "OIBDt3": 7.65e-30,
                "FIt": 3.08e-11,
                "FEt": 7.75e-10,
                "TDEPMAt": 9.147e-9,
                "TDEPMAt2": -122e-20,
                "EDEPBUt": 3.208e-8,
                "EDEPBUt2": -945e-19,
                "ZPFt": -2.22e-8,
                "dourt": 7.09e-11,
                "dgnp": 6.5e-13,
                "FAAB": -0.4256,
                "Public": 1.2128,
                "ruralare": -0.0887,
                "largcity": 0.0532,
            },
        },
        {
            # --- Step 2: Negative Probability Model (from Table 18b) ---
            "name": "negative_probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "OIBDt",
                "OIBDt2",
                "FIt",
                "FEt",
                "TDEPMAt",
                "TDEPMAt2",
                "EDEPBU",
                "EDEPBUt2",
                "ZPFt",
                "dourt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -1.2440,
                "OIBDt": 9.291e-9,
                "OIBDt2": -478e-20,
                "FIt": 1.22e-10,
                "FEt": 3.27e-10,
                "TDEPMAt": -2.27e-9,
                "TDEPMAt2": 1.57e-18,
                "EDEPBU": -2.22e-8,
                "EDEPBUt2": 5.72e-17,
                "ZPFt": 6.57e-12,
                "dourt": -912e-13,
                "dgnp": -604e-14,
                "FAAB": -1.3687,
                "Public": 0.5467,
                "ruralare": -0.1423,
                "largcity": -0.1418,
                "market": -1.7044,
                "marketw": 9.3471,
            },
        },
        {
            # --- Step 3: Positive Level Model (from Table 18c) ---
            "name": "positive_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "OIBDt",
                "OIBDt2",
                "OIBDt3",
                "FIt",
                "FEt",
                "TDEPMAt",
                "TDEPMAt2",
                "EDEPBUt",
                "EDEPBUt2",
                "ZPFt",
                "dourt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 2386081,
                "OIBDt": -0.4343,
                "OIBDt2": 2.34e-10,
                "OIBDt3": -292e-22,
                "FIt": 0.0252,
                "FEt": 0.2931,
                "TDEPMAt": 0.5699,
                "TDEPMAt2": -113e-12,
                "EDEPBUt": 1.4073,
                "EDEPBUt2": -1.39e-8,
                "ZPFt": -0.0715,
                "dourt": 0.00924,
                "dgnp": 0.000015,
                "FAAB": -728042,
                "Public": 5696818,
                "ruralare": -441121,
                "largcity": 886165,
                "market": 1.4414e8,
                "marketw": -7.027e7,
            },
        },
        {
            # --- Step 4: Negative Level Model (from Table 18d) ---
            "name": "negative_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "OIBDt",
                "OIBDt2",
                "FIt",
                "FEt",
                "TDEPMAt",
                "TDEPMAt2",
                "EDEPBUt",
                "EDEPBUt2",
                "ZPFt",
                "dourt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 931181,
                "OIBDt": -0.8272,
                "OIBDt2": -465e-15,
                "FIt": -0.1481,
                "FEt": 0.1743,
                "TDEPMAt": 0.7714,
                "TDEPMAt2": 4.03e-11,
                "EDEPBUt": 2.0254,
                "EDEPBUt2": 4.176e-9,
                "ZPFt": 0.00308,
                "dourt": -0.00008,
                "dgnp": -0.00001,
                "FAAB": 843477,
                "Public": -2780722,
                "ruralare": 9559.5,
                "largcity": -553991,
                "market": -1.203e8,
                "marketw": 8873028,
            },
        },
    ],
}
