OA_CONFIG = {
    "method": "MUNO",
    "steps": [
        {
            # --- Step 1: Multinomial Probability Model ---
            # Source: Table 19a: Multinomial Logit
            "name": "probability_model",
            "type": "Multinomial",
            "distribution": "clog-log",
            "input_variables": [
                "dourt",
                "GCt",
                "DTDEPMA",
                "DZPF",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": [-1.2269, 0.80162],
                "dourt": -54e-11,
                "GCt": 1.64e-9,
                "DTDEPMA": -0.1227,
                "DZPF": 0.08816,
                "realr": -1.6564,
                "FAAB": 0.44790,
                "Public": -0.0229,
                "ruralare": 0.03657,
                "largcity": 0.01973,
                "market": 0.29826,
                "marketw": -3.6165,
            },
        },
        {
            # --- Step 2: Positive Level Model ---
            # Source: Table 19b: Schweppe Bounded-Influence Regression (positive OA)
            "name": "positive_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "dourt",
                "GCt",
                "DTDEPMA",
                "DZPF",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 739683,
                "dourt": 0.00759,
                "GCt": 0.9970,
                "DTDEPMA": 41894.5,
                "DZPF": -67079.7,
                "realr": -2140373,
                "FAAB": -543333,
                "Public": 380865,
                "ruralare": 12606.5,
                "largcity": 153402,
                "market": 64384715,
                "marketw": 38827730,
            },
        },
        {
            # --- Step 3: Negative Level Model ---
            # Source: Table 19c: Schweppe Bounded-Influence Regression (negative OA)
            "name": "negative_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "dourt",
                "GCt",
                "DTDEPMA",
                "DZPF",
                "realr",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -241958,
                "dourt": -0.00093,
                "GCt": 0.9907,
                "DTDEPMA": 248546,
                "DZPF": 67000.4,
                "realr": 1052639,
                "FAAB": -73380.5,
                "Public": -843524,
                "ruralare": 37518.7,
                "largcity": -143196,
                "market": 2190197,
                "marketw": -5321761,
            },
        },
    ],
}
