TL_CONFIG = {
    "method": "LLN",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "Cumulative",
            "input_variables": [
                "OIBDt",
                "OIBDt2",
                "FIt",
                "FIt2",
                "FEt",
                "FEt2",
                "TDEPMAt",
                "TDEPMAt2",
                "EDEPBUt",
                "EDEPBUt2",
                "dourt",
                "dourt2",
                "ZPFt",
                "PALLOt_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -0.2181,
                "OIBDt": 2.906e-9,
                "OIBDt2": -857e-21,
                "FIt": 3.55e-10,
                "FIt2": -323e-22,
                "FEt": -2.25e-9,
                "FEt2": 4.97e-19,
                "TDEPMAt": -529e-12,
                "TDEPMAt2": 4.83e-19,
                "EDEPBUt": -1.52e-8,
                "EDEPBUt2": 9.04e-17,
                "dourt": -531e-12,
                "dourt2": 5.44e-20,
                "ZPFt": 4.24e-10,
                "PALLOt_1": 1.918e-8,
                "dgnp": 8.06e-13,
                "FAAB": 0.4153,
                "Public": -0.1320,
                "ruralare": -0.0277,
                "largcity": -0.0603,
                "market": 1.2303,
                "marketw": -4.4881,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "OIBDt",
                "OIBDt2",
                "FIt",
                "FIt2",
                "FEt",
                "FEt2",
                "TDEPMAt",
                "TDEPMAt2",
                "EDEPBUt",
                "EDEPBUt2",
                "dourt",
                "dourt2",
                "ZPFt",
                "PALLOt_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -87622.7,
                "OIBDt": 0.0909,
                "OIBDt2": -116e-13,
                "FIt": 0.0244,
                "FIt2": 4.71e-12,
                "FEt": -0.0239,
                "FEt2": 2.64e-12,
                "TDEPMAt": -0.0625,
                "TDEPMAt2": 1.25e-11,
                "EDEPBUt": -0.2130,
                "EDEPBUt2": 9.57e-10,
                "dourt": 0.0482,
                "dourt2": 3.9e-11,
                "ZPFt": -0.3147,
                "PALLOt_1": 0.3773,
                "dgnp": 2.253e-6,
                "FAAB": -11317.6,
                "Public": 726252,
                "ruralare": -23180.7,
                "largcity": 42745.8,
                "market": 83539967,
                "marketw": -1499138,
            },
        },
    ],
}
