OTA_CONFIG = {
    "method": "MUNO",
    "steps": [
        {
            # --- Step 1: Multinomial Probability Model ---
            # Source: Table 21a: Multinomial Logit
            "name": "probability_model",
            "type": "Multinomial",
            "distribution": "clog-log",
            "input_variables": [
                "PALLOt_1",
                "ZPFt",
                "TDEPMAt",
                "TDEPMAt2",
                "OIBDt",
                "OIBDt2",
                "EDEPBUt",
                "EDEPBUt2",
                "dourt",
                "TLt",
                "FIt",
                "FEt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept1": [0.37943, 0.66734],
                "PALLOt_1": 4.31e-9,
                "ZPFt": 635e-13,
                "TDEPMAt": -12e-10,
                "TDEPMAt2": 21e-19,
                "OIBDt": -19e-10,
                "OIBDt2": -87e-20,
                "EDEPBUt": 8.89e-9,
                "EDEPBUt2": 842e-20,
                "dourt": 1.22e-9,
                "TLt": 1.45e-8,
                "FIt": -95e-10,
                "FEt": 3.1e-9,
                "dgnp": -31e-14,
                "FAAB": 0.24556,
                "Public": -0.2513,
                "ruralare": 0.01285,
                "largcity": -0.0928,
                "market": -1.8691,
                "marketw": -1.6171,
            },
        },
        {
            # --- Step 2: Positive Level Model ---
            # Source: Table 21b: Schweppe Bounded-Influence Regression
            "name": "positive_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "PALLOt_1",
                "ZPFt",
                "TDEPMAt",
                "TDEPMAt2",
                "OIBDt",
                "OIBDt2",
                "EDEPBUt",
                "EDEPBUt2",
                "dourt",
                "TLt",
                "FIt",
                "FEt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -113233,
                "PALLOt_1": 0.0103,
                "ZPFt": -0.00958,
                "TDEPMAt": 0.0353,
                "TDEPMAt2": -548e-13,
                "OIBDt": -0.0114,
                "OIBDt2": 2.48e-11,
                "EDEPBUt": 0.2952,
                "EDEPBUt2": 3.03e-10,
                "dourt": 0.000416,
                "TLt": 0.9736,
                "FIt": -0.0530,
                "FEt": 0.2117,
                "dgnp": 2.384e-6,
                "FAAB": -29556.0,
                "Public": 345844,
                "ruralare": -9898.4,
                "largcity": 54708.4,
                "market": 1439326,
                "marketw": 14462364,
            },
        },
        {
            # --- Step 3: Negative Level Model ---
            # Source: Table 21c: Schweppe Bounded-Influence Regression
            "name": "negative_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "PALLOt_1",
                "ZPFt",
                "TDEPMAt",
                "OIBDt",
                "OIBDt2",
                "EDEPBUt",
                "EDEPBUt2",
                "dourt",
                "TLt",
                "FIt",
                "FEt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -1387497,
                "PALLOt_1": 0.5766,
                "ZPFt": -0.3916,
                "TDEPMAt": 0.2403,
                "OIBDt": -0.2255,
                "OIBDt2": -189e-13,
                "EDEPBUt": -0.7811,
                "EDEPBUt2": 9e-10,
                "dourt": 0.1481,
                "TLt": -0.00597,
                "FIt": -0.9500,
                "FEt": 0.7590,
                "dgnp": -5.63e-6,
                "FAAB": 1501982,
                "Public": 2318879,
                "ruralare": -15825.2,
                "largcity": -718388,
                "market": -3.193e8,
                "marketw": 29604280,
            },
        },
    ],
}
