ROT_CONFIG = {
    "method": "LLG",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "sumallozpft",
                "diffallozpft",
                "TDEPMAt",
                "TDEPMAt2",
                "OIBDt",
                "OIBDt2",
                "EDEPBUt",
                "EDEPBUt2",
                "OTAt",
                "OTAt2",
                "TDEPBUt",
                "TDEPBUt2",
                "dourt",
                "TLt",
                "FIt",
                "FEt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -4.3922,
                "sumallozpft": 1.847e-8,
                "diffallozpft": -1.3e-8,
                "TDEPMAt": 1.514e-9,
                "TDEPMAt2": -711e-21,
                "OIBDt": 1.024e-9,
                "OIBDt2": -158e-21,
                "EDEPBUt": -813e-12,
                "EDEPBUt2": 4.72e-17,
                "OTAt": -118e-12,
                "OTAt2": -38e-21,
                "TDEPBUt": -2.11e-9,
                "TDEPBUt2": -617e-19,
                "dourt": 2.26e-10,
                "TLt": -618e-12,
                "FIt": 6.53e-10,
                "FEt": -107e-12,
                "dgnp": 5.7e-12,
                "FAAB": -0.6675,
                "Public": 0.7457,
                "ruralare": -0.2892,
                "largcity": -0.0927,
                "market": -6.1357,
                "marketw": -9.2759,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumallozpft",
                "diffallozpft",
                "OIBDt",
                "EDEPBUt",
                "TDEPBUt",
                "dourt",
                "TLt",
                "FIt",
                "FEt",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -143891,
                "sumallozpft": 0.000576,
                "diffallozpft": -0.0152,
                "OIBDt": -0.00475,
                "EDEPBUt": 0.0684,
                "TDEPBUt": -0.1382,
                "dourt": 0.0141,
                "TLt": 0.0317,
                "FIt": -0.00049,
                "FEt": 0.0611,
                "dgnp": 2.93e-6,
                "FAAB": -212959,
                "Public": -313273,
                "ruralare": 173824,
                "largcity": 117139,
                "market": -4.98e7,
                "marketw": -2.043e7,
            },
        },
    ],
}
