# Table 2

SMA_CONFIG = {
    "method": "MUNO",
    "steps": [
        {
            # --- Step 1: Multinomial Probability Model ---
            "name": "probability_model",
            "type": "Multinomial",
            "distribution": "clog-log",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "TDEPMAt_1",
                "EDEPMAt",
                "EDEPMAt2",
                "MAt_1",
                "I_BUt_1",
                "I_BUt_12",
                "EDEPBUt_1",
                "EDEPBUt_12",
                "ddmtdmt_1",
                "ddmtdmt_12",
                "dcat_1",
                "ddmpat_1",
                "ddmpat_12",
                "dclt_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": [-2.6765, -1.1358],
                "sumcasht_1": 706e-13,
                "diffcasht_1": 263e-13,
                "TDEPMAt_1": 9.8e-9,
                "EDEPMAt": -24e-9,
                "EDEPMAt2": 586e-20,
                "MAt_1": -47e-12,
                "I_BUt_1": 889e-13,
                "I_BUt_12": 135e-22,
                "EDEPBUt_1": 1.15e-8,
                "EDEPBUt_12": -86e-18,
                "ddmtdmt_1": 4.67e-9,
                "ddmtdmt_12": -18e-19,
                "dcat_1": 648e-14,
                "ddmpat_1": 208e-12,
                "ddmpat_12": -28e-20,
                "dclt_1": 231e-13,
                "dgnp": 222e-13,
                "FAAB": 0.04094,
                "Public": -0.2894,
                "ruralare": -0.0192,
                "largcity": -0.0135,
                "market": -1.9939,
                "marketw": -3.7895,
            },
        },
        {
            # --- Step 2: Positive Level Model ---
            "name": "positive_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "EDEPMAt",
                "MAt_1",
                "I_BUt_1",
                "I_BUt_12",
                "EDEPBUt_1",
                "EDEPBUt_12",
                "ddmtdmt_1",
                "dcat_1",
                "ddmpat_1",
                "ddmpat_12",
                "dclt_1",
                "dclt_12",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -504825,
                "sumcasht_1": -0.00005,
                "diffcasht_1": 0.000050,
                "EDEPMAt": -4.3436,
                "MAt_1": 0.9754,
                "I_BUt_1": -0.00042,
                "I_BUt_12": -786e-16,
                "EDEPBUt_1": 0.0509,
                "EDEPBUt_12": 3.28e-11,
                "ddmtdmt_1": 0.0495,
                "dcat_1": 0.00176,
                "ddmpat_1": 0.00213,
                "ddmpat_12": -196e-13,
                "dclt_1": 0.000419,
                "dclt_12": 1.54e-13,
                "dgnp": 0.000020,
                "FAAB": -398468,
                "Public": 562959,
                "ruralare": -142176,
                "largcity": 252269,
                "market": -3.723e8,
                "marketw": -4.499e7,
            },
        },
        {
            # --- Step 3: Negative Level Model ---
            "name": "negative_level_model",
            "type": "Huber-Schweppes",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "sumcaclt_1",
                "diffcaclt_1",
                "TDEPMAt_1",
                "EDEPMAt",
                "EDEPMAt2",
                "MAt_1",
                "I_BUt_1",
                "EDEPBUt_1",
                "EDEPBUt_12",
                "ddmtdmt_1",
                "ddmpat_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -3346287,
                "sumcasht_1": -0.00013,
                "diffcasht_1": -0.00006,
                "sumcaclt_1": 0.000140,
                "diffcaclt_1": -0.00039,
                "TDEPMAt_1": 2.0626,
                "EDEPMAt": -3.6128,
                "EDEPMAt2": 1.47e-10,
                "MAt_1": 0.0327,
                "I_BUt_1": -0.00007,
                "EDEPBUt_1": 0.4997,
                "EDEPBUt_12": -5.56e-9,
                "ddmtdmt_1": 0.0547,
                "ddmpat_1": 0.0254,
                "dgnp": 0.000049,
                "FAAB": 360774,
                "Public": -210165,
                "ruralare": -236983,
                "largcity": 624165,
                "market": -5.095e8,
                "marketw": -1223215,
            },
        },
    ],
}
