EDEPBU_CONFIG = {
    "method": "LLG",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "IMAt",
                "BUt_1",
                "BUt_12",
                "dcat_1",
                "ddmpat_1",
                "dclt_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": -1.2451,
                "sumcasht_1": 1.88e-11,
                "diffcasht_1": -133e-13,
                "EDEPMAt": 1.178e-8,
                "EDEPMAt2": -242e-20,
                "SMAt": -223e-13,
                "IMAt": -803e-12,
                "BUt_1": 1.686e-9,
                "BUt_12": -203e-21,
                "dcat_1": 5.76e-11,
                "ddmpat_1": -739e-12,
                "dclt_1": 3.42e-11,
                "dgnp": 2.12e-12,
                "FAAB": -0.2074,
                "Public": 0.1722,
                "ruralare": 0.3906,
                "largcity": -0.7356,
                "market": 93.6332,
                "marketw": 2.5334,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "sumcaclt_1",
                "diffcaclt_1",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "SMAt2",
                "IMAt",
                "BUt_1",
                "ddmpat_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 335770,
                "sumcasht_1": -0.00011,
                "diffcasht_1": -0.00002,
                "sumcaclt_1": -0.00004,
                "diffcaclt_1": -0.00005,
                "EDEPMAt": 0.0472,
                "EDEPMAt2": -114e-13,
                "SMAt": -0.00276,
                "SMAt2": -191e-15,
                "IMAt": 0.00539,
                "BUt_1": 0.0219,
                "ddmpat_1": -0.00501,
                "dgnp": -3.8e-6,
                "FAAB": -39495.9,
                "Public": 113901,
                "ruralare": -13568.7,
                "largcity": -3824.7,
                "market": 1611088,
                "marketw": 10788356,
            },
        },
    ],
}
