IBU_CONFIG = {
    "method": "LLG",
    "steps": [
        {
            "name": "probability_model",
            "type": "Logistic",
            "distribution": "clog-log",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "IMAt",
                "EDEPBUt",
                "EDEPBUt2",
                "dcat_1",
                "ddmpat_1",
                "ddmpat_12",
                "dclt_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 1.2931,
                "sumcasht_1": 1.01e-10,
                "diffcasht_1": 8.53e-13,
                "EDEPMAt": 1.263e-8,
                "EDEPMAt2": -233e-20,
                "SMAt": 3.57e-10,
                "IMAt": -2.06e-9,
                "EDEPBUt": 2.861e-7,
                "EDEPBUt2": -951e-18,
                "dcat_1": 7.32e-11,
                "ddmpat_1": 6.89e-10,
                "ddmpat_12": -818e-21,
                "dclt_1": 1.72e-12,
                "dgnp": -385e-13,
                "FAAB": -0.1246,
                "Public": -0.6302,
                "ruralare": 0.2607,
                "largcity": -0.5440,
                "market": 2.3473,
                "marketw": 11.9200,
            },
        },
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "sumcaclt_1",
                "diffcaclt_1",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "IMAt",
                "EDEPBUt",
                "EDEPBUt2",
                "ddmpat_1",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 4406689,
                "sumcasht_1": -0.00155,
                "diffcasht_1": -0.00037,
                "sumcaclt_1": -0.00037,
                "diffcaclt_1": -0.00210,
                "EDEPMAt": -0.2362,
                "EDEPMAt2": 3.62e-11,
                "SMAt": -0.1643,
                "IMAt": 0.0973,
                "EDEPBUt": 2.9552,
                "EDEPBUt2": -1.38e-8,
                "ddmpat_1": 0.00783,
                "dgnp": -0.00005,
                "FAAB": -947456,
                "Public": 77806.5,
                "ruralare": -442724,
                "largcity": -711521,
                "market": 3.222e8,
                "marketw": -1.607e8,
            },
        },
    ],
}
