# Table 7
DCA_CONFIG = {
    "method": "HS",
    "steps": [
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "IMAt",
                "EDEPBUt",
                "EDEPBUt2",
                "IBUt",
                "IBUt2",
                "IBUt3",
                "dclt_1",
                "ddmpat_1",
                "ddmpat_12",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 2364307,
                "sumcasht_1": -0.00614,
                "diffcasht_1": 0.000392,
                "EDEPMAt": 0.1248,
                "EDEPMAt2": 8.92e-11,
                "SMAt": -0.5029,
                "IMAt": 0.4168,
                "EDEPBUt": 0.4543,
                "EDEPBUt2": -7.32e-9,
                "IBUt": 0.0192,
                "IBUt2": 2.73e-12,
                "IBUt3": 1.38e-21,
                "dclt_1": -0.00598,
                "ddmpat_1": -0.0176,
                "ddmpat_12": -219e-13,
                "dgnp": -0.00002,
                "FAAB": -1532929,
                "Public": 10225598,
                "ruralare": -386018,
                "largcity": 715615,
                "market": 1.2121e9,
                "marketw": -1.991e9,
            },
        }
    ],
}
