DCL_CONFIG = {
    "method": "HS",
    "steps": [
        {
            "name": "level_model",
            "type": "Huber-Schweppes",
            "distribution": "Heavy tail",
            "input_variables": [
                "sumcasht_1",
                "diffcasht_1",
                "EDEPMAt",
                "EDEPMAt2",
                "SMAt",
                "IMAt",
                "EDEPBUt",
                "EDEPBUt2",
                "IBUt",
                "IBUt2",
                "ddmpat_1",
                "ddmpat_12",
                "dcat",
                "dgnp",
                "FAAB",
                "Public",
                "ruralare",
                "largcity",
                "market",
                "marketw",
            ],
            "coefficients": {
                "Intercept": 4175407,
                "sumcasht_1": -0.00240,
                "diffcasht_1": -0.00034,
                "EDEPMAt": -0.1182,
                "EDEPMAt2": -167e-12,
                "SMAt": -0.1765,
                "IMAt": 0.1569,
                "EDEPBUt": 0.2457,
                "EDEPBUt2": -3.85e-8,
                "IBUt": 0.4451,
                "IBUt2": 1.04e-10,
                "ddmpat_1": -0.1212,
                "ddmpat_12": -376e-12,
                "ddmpat_13": -1.61e-19,
                "dcat": 0.6642,
                "dgnp": -0.00006,
                "FAAB": -226048,
                "Public": -911302,
                "ruralare": -60452.5,
                "largcity": 177176,
                "market": -3.093e7,
                "marketw": -1.076e9,
            },
        }
    ],
}
